{
  "branches": ["main"],
  "tagFormat": "${version}",
  "plugins": ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github'],
  "dryRun": true,
  "ci": false,
  "debug": true
}
