name: Hello World
on: [push, workflow_dispatch]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: prepare environment
      uses: actions/checkout@v2
    - uses: turtlebrowser/get-conan@main
    - name: configure conan
      run: |
        conan profile new default --detect &&
        conan profile update settings.compiler.libcxx=libstdc++11 default && 
        conan remote add me-repo https://markuseggenbauer.jfrog.io/artifactory/api/conan/me-conan -i 0 --force &&
        conan user -r me-repo -p ${{ secrets.CONAN_PASSWORD }} ${{ secrets.CONAN_USERNAME }}
    - name: build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsTxtPath: "${{ github.workspace }}/me_std/CMakeLists.txt"
        buildDirectory: "${{ github.workspace }}/../../build"
    - name: test
      run: |
        cd "${{ github.workspace }}/../../build/me_std" && ctest
        
