name: Hello World
on: [push, workflow_dispatch]
  
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: resolve_dependencies
      run: echo "conan install ."    
    - name: cmake_configure
      run: echo "mkdir build && cd build && cmake .."    
    - name: cmake_build
      run: echo "cd build && cmake --target all"    
    - name: ctest
      run: echo "cd build && ctest"    
